"""user

Revision ID: 8727a735a0be
Revises: b35ea99356b4
Create Date: 2023-09-25 22:16:50.379407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8727a735a0be'
down_revision: Union[str, None] = 'b35ea99356b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'competition', ['user_id'])
    op.create_foreign_key(None, 'competition', 'user', ['user_id'], ['id'])
    op.add_column('entry', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'entry', ['user_id'])
    op.create_foreign_key(None, 'entry', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.drop_constraint(None, 'entry', type_='unique')
    op.drop_column('entry', 'user_id')
    op.drop_constraint(None, 'competition', type_='foreignkey')
    op.drop_constraint(None, 'competition', type_='unique')
    op.drop_column('competition', 'user_id')
    # ### end Alembic commands ###
