"""user

Revision ID: b35ea99356b4
Revises: e47c752cc315
Create Date: 2023-09-25 22:12:24.405163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35ea99356b4'
down_revision: Union[str, None] = 'e47c752cc315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('competition_user_id_key', 'competition', type_='unique')
    op.drop_constraint('competition_user_id_fkey', 'competition', type_='foreignkey')
    op.drop_column('competition', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('competition', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('competition_user_id_fkey', 'competition', 'user', ['user_id'], ['id'])
    op.create_unique_constraint('competition_user_id_key', 'competition', ['user_id'])
    # ### end Alembic commands ###
